console.log('seeding sata');
exports.seed = async function (knex) {

  await knex('addresses').del()
  await knex('addresses').insert([
    {
      id: 1,
      restaurant_id: 1,
      street_address: '2618 NW 5th Ave',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 2,
      restaurant_id: 2,
      street_address: '400 NW 26th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 3,
      restaurant_id: 3,
      street_address: '337 NW 25th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 4,
      restaurant_id: 4,
      street_address: '545 NW 26th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 5,
      restaurant_id: 5,
      street_address: '591 NW 27th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 6,
      restaurant_id: 6,
      street_address: '2401 NW 5th Ave',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 7,
      restaurant_id: 7,
      street_address: '2308 NW 5th Ave',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 8,
      restaurant_id: 8,
      street_address: '415 NW 26th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 9,
      restaurant_id: 9,
      street_address: '446 NW 28th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 10,
      restaurant_id: 10,
      street_address: '251 NW 25th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 11,
      restaurant_id: 11,
      street_address: '316 NW 24th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 12,
      restaurant_id: 12,
      street_address: '380 NW 26th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 13,
      restaurant_id: 13,
      street_address: '347 NW 24th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    },
    {
      id: 14,
      restaurant_id: 14,
      street_address: '276 NW 26th St',
      city: 'Miami',
      state: 'FL',
      postal_code: '33127',
      country: 'USA',
    }
  ]);
};
