exports.seed = async function (knex) {

  await knex('restaurants').del()
  await knex('restaurants').insert([
    {
      id: 1,
      restaurant_name: 'Sushi Haven',
      cuisine: 'Japanese',
      description: 'Fresh and flavorful sushi creations',
      about: 'Sushi Haven offers a diverse menu of sushi rolls, sashimi, and Japanese delights.',
      contact_phone: '456-789-0123',
      contact_email: 'info@sushihaven.com',
      image_url: 'https://example.com/sushihaven.jpg',
    },
    {
      id: 2,
      restaurant_name: 'Tokyo Delights',
      cuisine: 'Japanese',
      description: 'Authentic Japanese dining experience in the heart of Tokyo',
      about: 'Tokyo Delights brings the traditional flavors of Japan with a modern twist, offering a variety of sushi, sashimi, and Japanese specialties.',
      contact_phone: '789-012-3456',
      contact_email: 'info@tokyodelights.com',
      image_url: 'https://example.com/tokyodelights.jpg',
    },
    {
      id: 3,
      restaurant_name: 'Curry Palace',
      cuisine: 'Indian',
      description: 'Rich and aromatic Indian curries',
      about: 'Curry Palace brings the authentic flavors of India with a variety of curry dishes.',
      contact_phone: '789-012-3456',
      contact_email: 'info@currypalace.com',
      image_url: 'https://example.com/currypalace.jpg',
    },
    {
      id: 4,
      restaurant_name: 'Spice Kingdom',
      cuisine: 'Indian',
      description: 'Experience the royal flavors of India at Spice Kingdom',
      about: 'Spice Kingdom is a haven for food enthusiasts seeking the authentic taste of Indian cuisine. Our menu showcases a splendid variety of aromatic curries, biryanis, and delectable desserts.',
      contact_phone: '456-789-0123',
      contact_email: 'info@currykingdom.com',
      image_url: 'https://example.com/currykingdom.jpg',
    },
    {
      id: 5,
      restaurant_name: 'Burger Bliss',
      cuisine: 'American',
      description: 'Classic American burgers done right',
      about: 'Burger Bliss is your destination for mouthwatering burgers and all-American favorites.',
      contact_phone: '234-567-8901',
      contact_email: 'info@burgerbliss.com',
      image_url: 'https://example.com/burgerbliss.jpg',
    },
    {
      id: 6,
      restaurant_name: 'Classic Diner Delight',
      cuisine: 'American',
      description: 'Indulge in the nostalgia of classic American diner fare',
      about: 'Classic Diner Delight takes you back to the golden age of diners with a menu full of timeless American favorites. From hearty burgers to comforting breakfast classics, there\'s something for everyone.',
      contact_phone: '789-012-3456',
      contact_email: 'info@classicdinerdelight.com',
      image_url: 'https://example.com/classicdinerdelight.jpg',
    },
    {
      id: 7,
      restaurant_name: 'Taco Fiesta',
      cuisine: 'Mexican',
      description: 'Tacos, burritos, and Mexican fiesta flavors',
      about: 'Taco Fiesta is the go-to spot for an authentic Mexican fiesta in every bite.',
      contact_phone: '890-123-4567',
      contact_email: 'info@tacofiesta.com',
      image_url: 'https://example.com/tacofiesta.jpg',
    },
    {
      id: 8,
      restaurant_name: 'Spicy Salsa',
      cuisine: 'Mexican',
      description: 'Bold and flavorful Mexican dishes',
      about: 'Spicy Salsa brings the heat with its mouthwatering selection of Mexican delicacies.',
      contact_phone: '987-654-3210',
      contact_email: 'info@spicysalsa.com',
      image_url: 'https://example.com/spicysalsa.jpg',
    },
    {
      id: 9,
      restaurant_name: 'Pizza Palace',
      cuisine: 'Italian',
      description: 'Delicious pizzas with a variety of toppings',
      about: 'Pizza Palace serves up mouthwatering pizzas with a wide selection of tasty toppings.',
      contact_phone: '543-210-9876',
      contact_email: 'info@pizzapalace.com',
      image_url: 'https://example.com/pizzapalace.jpg',
    },
    {
      id: 10,
      restaurant_name: 'Pasta Paradise',
      cuisine: 'Italian',
      description: 'Authentic Italian flavors in every dish',
      about: 'Pasta Paradise is your go-to place for delicious and traditional Italian cuisine.',
      contact_phone: '123-456-7890',
      contact_email: 'info@pastaparadise.com',
      image_url: 'https://example.com/pastaparadise.jpg',
    },
    {
      id: 11,
      restaurant_name: 'Vegan Vibes',
      cuisine: 'Vegetarian/Vegan',
      description: 'Plant-based delights for a healthier you',
      about: 'Vegan Vibes offers a menu full of delicious and wholesome plant-based dishes.',
      contact_phone: '321-654-0987',
      contact_email: 'info@veganvibes.com',
      image_url: 'https://example.com/veganvibes.jpg',
    },
    {
      id: 12,
      restaurant_name: 'Healthy Bites',
      cuisine: 'Vegetarian/Vegan',
      description: 'Nutritious and flavorful dishes for a healthy lifestyle',
      about: 'Healthy Bites is your destination for nutritious and delicious meals to support your well-being.',
      contact_phone: '210-987-6543',
      contact_email: 'info@healthybites.com',
      image_url: 'https://example.com/healthybites.jpg',
    },
    {
      id: 13,
      restaurant_name: 'Mediterranean Delight',
      cuisine: 'Mediterranean',
      description: 'Fresh and healthy Mediterranean cuisine',
      about: 'Mediterranean Delight offers a taste of the Mediterranean with fresh and nutritious dishes.',
      contact_phone: '567-890-1234',
      contact_email: 'info@mediterraneandelight.com',
      image_url: 'https://example.com/mediterraneandelight.jpg',
    },
    {
      id: 14,
      restaurant_name: 'The Oasis',
      cuisine: 'Mediterranean',
      description: 'Embark on a culinary journey through the flavors of the Mediterranean',
      about: 'The Oasis offers a delightful menu inspired by the sun-kissed shores of the Mediterranean. From fresh seafood to vibrant salads and savory kebabs, our dishes bring the essence of the region to your table.',
      contact_phone: '567-890-1234',
      contact_email: 'info@mediterraneanoasis.com',
      image_url: 'https://example.com/mediterraneanoasis.jpg',
    }
  ]);
};
